# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true

- task: PowerShell@2
  inputs:
    filePath: 'RetrieveDailyQuotes.ps1'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- script: |
    git add .
    git config user.email "imranak123@gmail.com"
    git config user.name "Imran Khan"
    git commit -m "Daily Quote retrieval : " + (date +"%d-%b-%Y")
    git push origin master
  workingDirectory: $(Build.SourcesDirectory)
  displayName: 'Git Commit and Tag from pipeline'
